# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3'

services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    restart: unless-stopped
    depends_on: 
      - db 
    # environment: 
      # REDIS_URL: redis:6379    
    networks: 
      - backend

  # Redis Service   
  db:
    image: postgres:latest
    container_name: postgres_db
    environment: 
      POSTGRES_PASSWORD: example-pass
    networks:
      - backend
    ports:
      - 5432:5432

networks:
  backend:    